== ABOUT

image:++./back-to-my-homepage-logo/back-to-my-homepage--scripted-final--with-gradient-applied--cropped.svg++[Back to my Homepage logo]

This is the new and https://inkscape.org/[Inkscape]-based version of
Shlomi Fish’s web graphics logo reading “Linux - Because Software Problems Should Not Cost Money”.

Its homepage is now at
http://www.shlomifish.org/art/back-to-my-homepage-2nd-ver/ .

The previous version, which was done using CorelDRAW, can be found on
https://www.shlomifish.org/art/linux_banner/[its page on Shlomi Fish’s site],
but its source CDR, and the available GIF file result may not be too usable.

== HOW TO USE

See the README file in the link:inkscape/[sub-directory]
for more information.

== LICENSE

As far as I'm (= Shlomi Fish) is concerned the intermediate and final .svg
files can be used under the CC-by-nc-sa version 4.0, or at your option,
any latee version (see
https://www.shlomifish.org/meta/copyrights/#cc_by_sa_nc_intr ). Crediting me as
the originator of the works will be appreciated, but not absolutely
necessary.
